name: 280blocker

on:
  push:
  schedule:
    - cron: "0 */1 * * *"

jobs:
  go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: 280blocker_adblock
        uses: wei/curl@master
        with:
          args: https://280blocker.net/files/280blocker_adblock_$(date +%Y%m).txt -o 280blocker/280blocker_adblock.txt
      - name: 280blocker_domain_ag
        uses: wei/curl@master
        with:
          args: https://280blocker.net/files/280blocker_domain_ag_$(date +%Y%m).txt -o 280blocker/280blocker_domain_ag.txt
      - name: get today date
        id: date
        run: export TZ='Asia/Taipei' && echo "::set-output name=date::$(date +'%Y-%m-%d-%H')"
      - name: push
        uses: actions-go/push@v1
        with:
          commit-files: 280blocker/280blocker_domain_ag.txt, 280blocker/280blocker_adblock.txt
          commit-message: 🤖 update 280blocker_${{ steps.date.outputs.date }}
